#version: 2
#updates:
#- package-ecosystem: nuget
#  directory: "/Framework"
#  schedule:
#    interval: daily
#    time: "11:00"
#  open-pull-requests-limit: 99
#  target-branch: master
#  labels:
#  - dependencies
#  - dependabot
